authapp/urls.py
from django.urls import path

import authapp.views as controller


app_name = 'authapp'

urlpatterns = [
    path('', controller.redirect_to_login, name='index'),
    path('add_sub/<int:id>', controller.add_subscribe, name='add_sub'),
    path('del_sub/<int:id>', controller.del_subscribe, name='del_sub'),
    path('login/', controller.login, name='login'),
    path('logout/', controller.logout, name='logout'),
    path('register/', controller.register, name='register'),
    path('edit/', controller.edit, name='edit'),
    path('profile/<int:id>', controller.profile, name='profile'),
]

group_up/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as controller

urlpatterns = [
    path('', controller.index, name='index'),
    path('dev/', controller.dev, name='dev'),
    path('contact/', controller.contact, name='contact'),

    path('groups/', include('groupsapp.urls', namespace='groups')),
    path('group/', include('mainapp.urls', namespace='group')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('shear/', include('shearapp.urls', namespace='shear')),

    path('admin/', admin.site.urls, name='admin'),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_ROOT,
        documents_root=settings.MEDIA_ROOT
    )

groupsapp/urls.py
from django.urls import path
import groupsapp.views as controller


app_name = 'groupsapp'

urlpatterns = [
    path('', controller.index, name='index'),
    path('add/<int:id>/<str:key>', controller.add_user, name='add_user'),
    path('remove/<int:id>/<str:key>', controller.remove_user, name='remove_user'),
    path('group/<int:id>/<str:key>', controller.group, name='group'),
    path('new_group/', controller.new_group, name='new_group'),
    path('task/<int:id>/<str:key>', controller.task, name='task'),
    path('all_tasks/<str:key>', controller.all_tasks, name='all_tasks'),
    path('new_task/<int:id>', controller.new_task, name='new_task'),
    path('edit_group/<int:id>/<str:key>', controller.edit_group, name='edit_group'),
    path('user_list/<int:id>/<str:key>', controller.user_list, name='user_list'),
    path('edit_permission/<int:id>/<int:user_id>/<str:permission>', controller.edit_permission, name='edit_permission'),
    path('edit_task_status/<int:id>/<str:key>/<str:status>', controller.edit_task_status, name='edit_task_status'),
]

authapp/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser


# Create your models here.
class CustomUser(AbstractUser):
    profile_photo = models.ImageField(upload_to='user_photo', verbose_name='user_profile_photo', blank=True)
    age = models.PositiveIntegerField(verbose_name='user age', blank=True, default=18)
    about_me = models.TextField(max_length=1000, verbose_name='description', blank=True)
    vk_url = models.URLField(max_length=250, blank=True)
    telegram_url = models.URLField(max_length=250, blank=True)
    instagram_url = models.URLField(max_length=250, blank=True)
    facebook_url = models.URLField(max_length=250, blank=True)


class UserSubscribe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user')
    subscribe = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='subscribe')

authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from authapp.models import CustomUser


class LoginForm(AuthenticationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class RegisterForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'age', 'password1', 'password2', 'email', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class UpdateForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'age', 'password', 'email', 'first_name', 'last_name', 'about_me', 'vk_url', 'telegram_url', 'instagram_url', 'facebook_url')

    def __init__(self, *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

            if field_name == 'password':
                field.widget = forms.HiddenInput()

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.http import HttpRequest
from .forms import LoginForm, RegisterForm, UpdateForm
from django.contrib import auth
from django.urls import reverse
from django.conf import settings
from authapp.models import CustomUser, UserSubscribe


# Create your views here.
def redirect_to_login(request: HttpRequest):
    return HttpResponseRedirect(reverse('auth:login'))


def login(request: HttpRequest):
    login_form = LoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect('/')
    content = {
        'login_form': login_form,
    }
    return render(request, 'authapp/login.html', content)


def logout(request: HttpRequest):
    auth.logout(request)
    return HttpResponseRedirect('/')


def register(request: HttpRequest):
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = RegisterForm()

    content = {
        'reg_form': register_form,
    }

    return render(request, 'authapp/register.html', content)


def edit(request: HttpRequest):
    if request.method == 'POST':
        update_form = UpdateForm(request.POST, instance=request.user)

        if update_form.is_valid():
            update_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        update_form = UpdateForm(instance=request.user)

    content = {
        'update_form': update_form,
    }

    return render(request, 'authapp/edit.html', content)


def profile(request: HttpRequest, id: int):
    page_user = CustomUser.objects.filter(id=id)
    user_is_subscribe = False
    all_subs = None
    if page_user:
        page_user = get_object_or_404(CustomUser, id=id)
        user_is_exists = True
        all_subs = UserSubscribe.objects.filter(subscribe=page_user.id)
        subscribe = UserSubscribe.objects.filter(user=request.user.id, subscribe=page_user.id)
        if subscribe:
            user_is_subscribe = True
    else:
        user_is_exists = False

    context = {
        'user_is_subscribe': user_is_subscribe,
        'user_is_exists': user_is_exists,
        'page_id': id,
        'page_user': page_user,
        'all_subs': all_subs,
    }

    return render(request, 'authapp/profile.html', context)


def add_subscribe(request: HttpRequest, id: int):
    if request.user.is_authenticated:
        id_sub_user = get_object_or_404(CustomUser, id=id)
        is_exist = UserSubscribe.objects.filter(user=request.user.id, subscribe=id_sub_user.id)
        if not is_exist:
            subscriber = UserSubscribe(user=request.user, subscribe=id_sub_user)
            subscriber.save()

    return HttpResponseRedirect(reverse('auth:profile', args=[id]))


def del_subscribe(request: HttpRequest, id: int):
    if request.user.is_authenticated:
        id_sub_user = get_object_or_404(CustomUser, id=id)
        is_exist = UserSubscribe.objects.filter(user=request.user.id, subscribe=id_sub_user.id)
        if is_exist:
            subscribe = get_object_or_404(UserSubscribe, user=request.user.id, subscribe=id_sub_user.id)
            subscribe.delete()

    return HttpResponseRedirect(reverse('auth:profile', args=[id]))

authapp/templates/authapp/edit.html
{% extends 'authapp/layout.html' %}
{% load static %}

{% block content %}
    <div class="auth_forms">
        <div class="edit_form">
            <h3>Profile changes</h3>
            <form action="{% url 'auth:edit' %}" method="post">
                {% csrf_token %}
                {{ update_form.as_p }}
                <div class="auth_submit_block">
                    <p>
                        <input type="submit" value="EDIT" class="auth_forms_submit_button">
                    </p>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ page_title }}
        {% endblock %}
    </title>
    {% block css %}
        <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,40.." rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}

    {% block js %}

    {% endblock %}

</head>
<body>
<div class="container">
    {% block header %}
    <div class="header">
        <a href="{% url 'index' %}"><img class="logo" src="{% static 'img/logo.svg' %}" alt="logo"></a>
        <ul class="menu">
            <li class="menu-list">
                <a href="{% url 'index' %}" class="menu-link">Home</a>
            </li>
            <li class="menu-list">
                <a href="{% url 'groups:index' %}" class="menu-link">Groups</a>
            </li>
            <li class="menu-list">
                <a href="{% url 'contact' %}" class="menu-link">Contact</a>
            </li>
            {% if user.is_authenticated %}
                <li class="menu-list">
                    <a href="{% url 'auth:profile' id=request.user.id %}" class="menu-link menu-link-active">My profile</a>
                </li>
                <li class="menu-list">
                    <a href="{% url 'auth:logout' %}" class="menu-link">Logout</a>
                </li>
            {% else %}
                <li class="menu-list">
                    <a href="{% url 'auth:login' %}" class="menu-link menu-link-active">Login</a>
                </li>
                <li class="menu-list">
                    <a href="{% url 'auth:register' %}" class="menu-link menu-link-active">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
    {% endblock %}
    <div class="content">
        {% block content %}

        {% endblock %}
    </div>
    {% block footer %}
    <div class="footer">
        <div class="footer_up">
            <div class="footer_contact">
                <h6>CONTACT US</h6>
                <p>QJJR+3R Central Administrative Okrug, Moscow</p>
                <p>Talk to us on +7(123)456-78-90 info@info.com</p>
            </div>
            <div class="footer_useful_info">
                <h6>USEFUL INFORMATION</h6>
                <div class="footer_useful_info_block">
                    <div class="footer_useful_info_links">
                        <a href="{% url 'dev' %}">About Us</a>
                        <a href="{% url 'dev' %}">API</a>
                        <a href="{% url 'dev' %}">Documentation</a>
                    </div>
                    <div class="footer_useful_info_links">
                        <a href="{% url 'dev' %}" target="_blank">Trello</a>
                        <a href="{% url 'dev' %}" target="_blank">Github</a>
                        <a href="{% url 'dev' %}" target="_blank">Seo</a>
                    </div>
                </div>
            </div>
            <div class="footer_touch_email">
                <h6>LET’S STAY IN TOUCH!</h6>
                <p>Subscribe to know about our latest news, products and special offers just for subscribers</p>
                <label>
                    <input type="email" class="footer_touch_email_input" placeholder="your email address">
                </label>
            </div>
        </div>
        <div class="footer_down">
            <p>© Copyright - GROUP UP 2019. All Rights Reserved.</p>
            <div style="display: flex">
                <a href="{% url 'dev' %}" target="_blank"><img src="{% static 'img/facebook_link_logo.png' %}" alt="facebook logo"></a>
                <a href="{% url 'dev' %}" target="_blank"><img src="{% static 'img/twitter_link_logo.png' %}" alt="twitter logo"></a>
                <a href="{% url 'dev' %}" target="_blank"><img src="{% static 'img/google_link_logo.png' %}" alt="google logo"></a>
                <a href="{% url 'dev' %}" target="_blank"><img src="{% static 'img/patreon_link_logo.png' %}" alt="patreon logo"></a>
            </div>
            <a href="{% url 'dev' %}" class="footer_down_privacy_link">TERMS & CONDITIONS / PRIVACY POLICY & COOKIES</a>
        </div>
    </div>
    {% endblock %}
</div>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/layout.html' %}
{% load static %}

{% block content %}
    <div class="auth_forms">
        <div class="login_form">
            <h3>Authentication</h3>
            <form action="{%  url 'auth:login' %}" method="post">
                {% csrf_token %}
                {{ login_form.as_p }}
                <div class="auth_submit_block">
                    <p>
                        <input type="submit" value="LOGIN" class="auth_forms_submit_button">
                    </p>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

authapp/templates/authapp/profile.html
{% extends 'authapp/layout.html' %}
{% load static %}

{% block content %}
    {% if user_is_exists %}
    <div class="main_profile">
        <div class="profile_left_block">
            <div class="profile_photo" style="background-color: #6c6c6c"></div>
            <div class="del_line" style="margin-top: 10px"></div>
            <div class="social_media">
                <a href="{{ page_user.vk_url }}" class="social_link" target="_blank"><img src="{% static 'img/vk_icon.svg' %}" alt=""></a>
                <a href="{{ page_user.instagram_url }}" class="social_link" target="_blank"><img src="{% static 'img/instagram_icon.svg' %}" alt=""></a>
                <a href="{{ page_user.telegram_url }}" class="social_link" target="_blank"><img src="{% static 'img/telegram_icon.svg' %}" alt=""></a>
                <a href="{{ page_user.facebook_url }}" class="social_link" target="_blank"><img src="{% static 'img/facebook_icon.svg' %}" alt=""></a>
            </div>
            <div class="del_line"></div>
            <div class="profile_subscribers_block">
                <p class="profile_subscribers_text">Subscribers:</p>
                <div class="profile_subscribers">
                    {% for i in all_subs %}
                        <a class="profile_each_sub" href="{% url 'auth:profile' id=i.user.id %}">
                            <div class="profile_each_sub_photo"></div>
                            <div style="display: flex; flex-direction: column">
                                <p class="profile_each_sub_info">{{ i.user.first_name }}</p>
                                <p class="profile_each_sub_info">{{ i.user.last_name }}</p>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="profile_right_block">
            <div class="profile_name">
                <div style="display: flex">
                    <h4>{{ page_user.first_name }}</h4>
                    <div class="profile_online_dot"></div>
                </div>
                <h4>{{ page_user.last_name }}</h4>
            </div>
            <div class="del_line" style="margin-top: 10px; width: 660px"></div>
            {% if page_id is request.user.id and user.is_authenticated%}
            <div class="profile_buttons_block">
                <a href="{% url 'auth:edit' %}" class="profile_button">Edit profile</a>
                <a href="{% url 'groupsapp:index' %}" class="profile_button">Groups</a>
                <a href="" class="profile_button">Shear</a>
            </div>
            <div class="del_line" style="margin-top: 10px; width: 660px"></div>
            {% else %}
            <div class="profile_buttons_block">
                {% if user.is_authenticated %}
                    {% if user_is_subscribe %}
                        <a href="{% url 'authapp:del_sub' id=page_user.id %}" class="profile_button">Unsubscribe</a>
                    {% else %}
                        <a href="{% url 'authapp:add_sub' id=page_user.id %}" class="profile_button">Subscribe</a>
                    {% endif %}
                    <a href="" class="profile_button">Write</a>
                {% endif %}
                <a href="" class="profile_button">Shear</a>
            </div>
            <div class="del_line" style="margin-top: 10px; width: 660px"></div>
            {% endif %}
            <div class="profile_main_info">
                <p class="profile_main_info_text">Email: {{ page_user.email }}</p>
                <p class="profile_main_info_text">Age: {{ page_user.age }}</p>
                <p class="profile_main_info_text">About me: {{ page_user.about_me }}</p>
            </div>
            <div class="del_line" style="width: 660px"></div>
            <div class="profile_activity">
                <h4 class="profile_activity_h">Last activity:</h4>
                <div class="last_profile_activity">
                    <p class="last_profile_activity_text">User have been registered at {{ page_user.date_joined }} </p>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="pass">
        <h1>user does not exist</h1>
    </div>
    {% endif %}
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/layout.html' %}
{% load static %}

{% block content %}
    <div class="auth_forms">
        <div class="register_form">
            <h3>Registration</h3>
            <form action="{% url 'auth:register' %}" method="post">
                {% csrf_token %}
                {{ reg_form.as_p }}
                <div class="auth_submit_block">
                    <p>
                        <input type="submit" value="REGISTER" class="auth_forms_submit_button">
                    </p>
                </div>
            </form>
        </div>
    </div>
{% endblock %}