authapp/urls.py
from django.urls import path

import authapp.views as controller


app_name = 'authapp'

urlpatterns = [
    path('', controller.redirect_to_login, name='index'),
    path('add_sub/<int:id>', controller.add_subscribe, name='add_sub'),
    path('del_sub/<int:id>', controller.del_subscribe, name='del_sub'),
    path('login/', controller.login, name='login'),
    path('logout/', controller.logout, name='logout'),
    path('register/', controller.register, name='register'),
    path('edit/', controller.edit, name='edit'),
    path('profile/<int:id>', controller.profile, name='profile'),
]

group_up/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as controller

urlpatterns = [
    path('', controller.index, name='index'),
    path('dev/', controller.dev, name='dev'),
    path('contact/', controller.contact, name='contact'),

    path('groups/', include('groupsapp.urls', namespace='groups')),
    path('group/', include('mainapp.urls', namespace='group')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('shear/', include('shearapp.urls', namespace='shear')),

    path('admin/', admin.site.urls, name='admin'),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_ROOT,
        documents_root=settings.MEDIA_ROOT
    )

groupsapp/urls.py
from django.urls import path
import groupsapp.views as controller


app_name = 'groupsapp'

urlpatterns = [
    path('', controller.index, name='index'),
    path('add/<int:id>/<str:key>', controller.add_user, name='add_user'),
    path('remove/<int:id>/<str:key>', controller.remove_user, name='remove_user'),
    path('group/<int:id>/<str:key>', controller.group, name='group'),
    path('new_group/', controller.new_group, name='new_group'),
    path('task/<int:id>/<str:key>', controller.task, name='task'),
    path('all_tasks/<str:key>', controller.all_tasks, name='all_tasks'),
    path('new_task/<int:id>', controller.new_task, name='new_task'),
    path('edit_group/<int:id>/<str:key>', controller.edit_group, name='edit_group'),
    path('user_list/<int:id>/<str:key>', controller.user_list, name='user_list'),
    path('edit_permission/<int:id>/<int:user_id>/<str:permission>', controller.edit_permission, name='edit_permission'),
    path('edit_task_status/<int:id>/<str:key>/<str:status>', controller.edit_task_status, name='edit_task_status'),
]

groupsapp/models.py
from django.db import models
from django.conf import settings
import uuid

# Create your models here.


class Group(models.Model):
    name = models.CharField(max_length=30, verbose_name='Group name')
    profile_photo = models.ImageField(upload_to='group_photo', verbose_name='Group_profile_photo', blank=True)
    short_desc = models.CharField(verbose_name='short_description', max_length=60, blank=True)
    description = models.TextField(verbose_name='description', blank=True)
    uuid = models.UUIDField(verbose_name='uuid', blank=True, default=uuid.uuid4())


class Available(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='available')
    groups = models.ForeignKey(Group, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='quantity', default=0)
    add_datetime = models.DateTimeField(verbose_name='add_datetime', auto_now_add=True)


class Task(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='task_name', max_length=60)
    description = models.TextField(verbose_name='description')
    is_done = models.BooleanField(verbose_name='is_done', default=False)


class Permission(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_creator = models.BooleanField(verbose_name='is_creator', default=False)
    is_admin = models.BooleanField(verbose_name='is_admin', default=False)
    is_moderator = models.BooleanField(verbose_name='is_moderator', default=False)
    add_datetime = models.DateTimeField(verbose_name='add_datetime', auto_now_add=True)

groupsapp/forms.py
from django import forms
from groupsapp.models import Group, Available, Task


class GroupAddForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(GroupAddForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

            if field_name == 'uuid':
                field.widget = forms.HiddenInput()


class TaskEditForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TaskEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

            if field_name == 'group' or field_name == 'is_done':
                field.widget = forms.HiddenInput()


class GroupEditForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(GroupEditForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

            if field_name == 'uuid':
                field.widget = forms.HiddenInput()

groupsapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponseRedirect
from groupsapp.models import Group, Available, Task, Permission
from django.urls import reverse
from groupsapp.forms import GroupAddForm, TaskEditForm, GroupEditForm

# Create your views here.


def add_user(request: HttpRequest, id: int, key: str):
    group = None
    if request.user.is_authenticated:
        group = get_object_or_404(Group, pk=id)

        certain_group = Available.objects.filter(groups__id=id, user=request.user)

        if certain_group:
            pass
        else:
            if key == str(group.uuid):
                new_available = Available(user=request.user, groups=group)
                new_available.quantity += 1
                new_available.save()
                new_permission = Permission(group=group, user=request.user)
                new_permission.save()

    return HttpResponseRedirect(reverse('groups:group', args=[group.id, group.uuid]))


def remove_user(request: HttpRequest, id: int, key: str):
    if request.user.is_authenticated:
        able = get_object_or_404(Available, groups=id, user=request.user)
        if str(able.groups.uuid) == key:
            able.delete()

    return HttpResponseRedirect(reverse('groups:index'))


def index(request: HttpRequest):
    if request.user.is_authenticated:
        group = Available.objects.filter(user=request.user)
        if not group:
            group = False
    else:
        group = False

    context = {
        'group': group
    }

    return render(request, 'groupsapp/index.html', context)


def group(request: HttpRequest, id: int, key: str):
    # available_groups = get_object_or_404(Available, groups=id, user=request.user.id)
    uuid = True
    all_users = False
    permission = None
    if request.user.is_authenticated:
        available_groups = Available.objects.filter(groups=id, user=request.user.id)
        all_users = Available.objects.filter(groups=id)
        if not available_groups:
            group = False
        else:
            group = get_object_or_404(Group, pk=id)
            if str(group.uuid) != key:
                group = False
                uuid = False
            else:
                uuid = group.uuid
                permission = get_object_or_404(Permission, group=group, user=request.user.id)
    else:
        group = False
        available_groups = False

    context = {
        'permission': permission,
        'group': group,
        'available': available_groups,
        'uuid': uuid,
        'all_users': all_users,
    }

    return render(request, 'groupsapp/group.html', context)


def new_group(request: HttpRequest):
    if request.method == 'POST':
        group_form = GroupAddForm(request.POST, request.FILES)
        if group_form.is_valid():
            data = group_form.cleaned_data.get("uuid")
            group_form.save()
            able = get_object_or_404(Group, uuid=data)
            new_available = Available(user=request.user, groups=able)
            new_available.quantity += 1
            new_available.save()
            new_permission = Permission(group=able, user=request.user, is_creator=True)
            new_permission.save()
            return HttpResponseRedirect(reverse('groups:index'))
    else:
        group_form = GroupAddForm()

    context = {
        'group_form': group_form,
    }

    return render(request, 'groupsapp/new_group.html', context)


def task(request: HttpRequest, id: int, key: str):
    authenticated = False
    user_is_valid = False
    group_is_valid = False
    task_is_valid = False
    task_is = None
    if request.user.is_authenticated:
        authenticated = True
        available_group = Group.objects.filter(uuid=key)
        if available_group:
            group_is_valid = True
            available_group = get_object_or_404(Group, uuid=key)
            available_user = Available.objects.filter(user=request.user.id, groups=available_group.id)
            if available_user:
                user_is_valid = True
                task_is = Task.objects.filter(id=id, group=available_group.id)
                if task_is:
                    task_is_valid = True
                    task_is = get_object_or_404(Task, id=id, group=available_group.id)

    context = {
        'task': task_is,
        'task_is_valid': task_is_valid,
        'authenticated': authenticated,
        'group_is_valid': group_is_valid,
        'user_is_valid': user_is_valid,
    }

    return render(request, 'groupsapp/task.html', context)


def all_tasks(request: HttpRequest, key: str):
    authenticated = False
    key_is_valid = False
    user_is_valid = False
    tasks = None
    group_is = None
    if request.user.is_authenticated:
        authenticated = True
        group_is = Group.objects.filter(uuid=key)
        if group_is:
            key_is_valid = True
            group_is = get_object_or_404(Group, uuid=key)
            available = Available.objects.filter(user=request.user.id, groups=group_is.id)
            if available:
                user_is_valid = True
                tasks = Task.objects.filter(group=group_is.id)

    context = {
        'authenticated': authenticated,
        'key_is_valid': key_is_valid,
        'user_is_valid': user_is_valid,
        'tasks': tasks,
        'group_is': group_is,
    }

    return render(request, 'groupsapp/all_tasks.html', context)


def new_task(request: HttpRequest, id: int):
    task_form = None
    authenticated = False
    user_is_valid = False
    if request.user.is_authenticated:
        authenticated = True
        available = Available.objects.filter(user=request.user.id, groups=id)
        if available:
            permission = get_object_or_404(Permission, group=id, user=request.user.id)
            if permission.is_admin or permission.is_moderator or permission.is_creator:
                user_is_valid = True
                if request.method == 'POST':
                    task_form = TaskEditForm(request.POST, request.FILES)
                    if task_form.is_valid():
                        task_form.group = id
                        task_form.save()
                        return HttpResponseRedirect(reverse('groups:all_tasks', args=[permission.group.uuid]))
                else:
                    task_form = TaskEditForm(initial={'is_done': False, 'group': id})

    context = {
        'task_form': task_form,
        'authenticated': authenticated,
        'user_is_valid': user_is_valid,
    }

    return render(request, 'groupsapp/new_task.html', context)


def edit_group(request: HttpRequest, id: int, key: str):
    authenticated = False
    group_form = None
    key_is_valid = False
    user_is_valid = False
    uuid = None
    group_id = None
    if request.user.is_authenticated:
        authenticated = True
        available_user = Available.objects.filter(user=request.user.id, groups=id)
        if available_user:
            permission = get_object_or_404(Permission, group=id, user=request.user.id)
            if permission.is_admin or permission.is_creator:
                user_is_valid = True
                available_key = Group.objects.filter(uuid=key)
                if available_key:
                    uuid = available_key[0].uuid
                    group_id = available_key[0].id
                    key_is_valid = True
                    if request.method == 'POST':
                        group_form = GroupEditForm(request.POST, instance=available_key[0])
                        if group_form.is_valid():
                            group_form.save()
                            return HttpResponseRedirect(reverse('groups:group', args=[group_id, uuid]))
                    else:
                        group_form = GroupEditForm(instance=available_key[0])

    context = {
        'group_form': group_form,
        'authenticated': authenticated,
        'key_is_valid': key_is_valid,
        'user_is_valid': user_is_valid,
        'uuid': uuid,
        'group_id': group_id,
    }

    return render(request, 'groupsapp/edit_group.html', context)


def user_list(request: HttpRequest, id: int, key: str):
    authenticated = False
    group_form = None
    key_is_valid = False
    user_is_valid = False
    uuid = None
    group_id = None
    user = None
    users = None
    permission = None
    if request.user.is_authenticated:
        authenticated = True
        available_user = Available.objects.filter(user=request.user.id, groups=id)
        if available_user:
            permission = get_object_or_404(Permission, group=id, user=request.user.id)
            if permission:
                user_is_valid = True
                available_key = Group.objects.filter(uuid=key)
                if available_key:
                    uuid = available_key[0].uuid
                    group_id = available_key[0].id
                    key_is_valid = True
                    users = Permission.objects.filter(group=id)

    context = {
        'authenticated': authenticated,
        'key_is_valid': key_is_valid,
        'user_is_valid': user_is_valid,
        'uuid': uuid,
        'group_id': group_id,
        'users': users,
        'permission': permission,
    }

    return render(request, 'groupsapp/user_list.html', context)


def edit_permission(request: HttpRequest, id: int, user_id: int, permission: str):
    cur_group = None
    if request.user.is_authenticated:
        user_permission = get_object_or_404(Permission, group=id, user=request.user.id)
        edit_user = get_object_or_404(Permission, group=id, user=user_id)
        cur_group = get_object_or_404(Group, id=id)
        if user_permission.is_admin:
            if permission == 'moderator':
                if not edit_user.is_admin and not edit_user.is_creator:
                    edit_user.is_admin = False
                    edit_user.is_moderator = True
                    edit_user.save()

groupsapp/templates/groupsapp/all_tasks.html
{% extends 'groupsapp/layout.html' %}
{% load static %}

{% block content %}
        {% if authenticated %}
            {% if key_is_valid and user_is_valid %}
                <div class="main_group">
                    <div class="user_list">
                    <ul style="list-style-type: none">
                        {% for i in tasks %}
                            <div class="user_card">
                                <div style="margin: 10px; height: 100px; width: 310px">
                                    <div class="all_task_name">
                                        <a class="all_task_name_text_hover" href="{% url 'groups:task' id=i.id key=group_is.uuid %}">{{ i.name }}</a>
                                    </div>
                                    <div class="all_task_status">
                                        {% if i.is_done %}
                                            <a class="all_task_name_text_hover" href="{% url 'groups:task' id=i.id key=group_is.uuid %}">Status: is done</a>
                                            <div class="all_task_status_done_dot"></div>
                                        {% else %}
                                             <a class="all_task_name_text_hover" href="{% url 'groups:task' id=i.id key=group_is.uuid %}">Status: is undone</a>
                                            <div class="all_task_status_undone_dot"></div>
                                        {% endif %}
                                    </div>
                                    <div class="all_task_edit_status_block">
                                        <a class="all_task_edit_status_button" href="{% url 'groups:edit_task_status' id=i.id key=group_is.uuid status="undone" %}">undone</a>
                                        <a class="all_task_edit_status_button" href="{% url 'groups:edit_task_status' id=i.id key=group_is.uuid status="done" %}">done</a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </ul>
                    </div>
                </div>
            {% elif not user_is_valid %}
                <div class="pass">
                    <p class="pass_text">You don't have access to this group</p>
                </div>
            {% else %}
                <div class="pass">
                    <p class="pass_text">You don't have access, key was wrong</p>
                </div>
            {% endif %}
        {% else %}
            <div class="pass">
                <div class="pass">
                    <p class="pass_text">You must login or register to get access to group</p>
                    <div style="display: flex; justify-content: center; margin-top: 20px">
                        <a href="{% url 'auth:login' %}" class="pass_button" style="margin-right: 20px">Login</a>
                        <a href="{% url 'auth:register' %}" class="pass_button">Register</a>
                    </div>
                </div>
            </div>
        {% endif %}
{% endblock %}

groupsapp/templates/groupsapp/edit_group.html
{% extends 'groupsapp/layout.html' %}
{% load static %}

{% block content %}
    {% if authenticated %}
        {% if key_is_valid %}
            <div class="auth_forms">
                <div class="edit_form">
                    <h3>Group changes</h3>
                    <form action="{% url 'groups:edit_group' id=group_id key=uuid%}" method="post">
                        {% csrf_token %}
                        {{ group_form.as_p }}
                        <div class="auth_submit_block">
                            <p>
                                <input type="submit" value="EDIT" class="auth_forms_submit_button">
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        {% elif  user_is_valid %}
            <div class="pass">
                <p class="pass_text">You don't have access key was wrong</p>
            </div>
        {% else %}
            <div class="pass">
                <p class="pass_text">You don't have access to this group</p>
            </div>
        {% endif %}
    {% else %}
        <div class="pass">
            <div class="pass">
                <p class="pass_text">You must login or register to get access to group</p>
                <div style="display: flex; justify-content: center; margin-top: 20px">
                    <a href="{% url 'auth:login' %}" class="pass_button" style="margin-right: 20px">Login</a>
                    <a href="{% url 'auth:register' %}" class="pass_button">Register</a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

groupsapp/templates/groupsapp/group.html
{% extends 'groupsapp/layout.html' %}
{% load static %}

{% block content %}
    {% if user.is_authenticated and not uuid %}
        <div class="pass">
            <p class="pass_text">You don't have access key was wrong</p>
        </div>
    {% elif user.is_authenticated and not group %}
        <div class="pass">
            <p class="pass_text">You don't have access to this group</p>
        </div>
    {% elif user.is_authenticated %}
        <div class="main_group">
            <div class="group_info">
                <div class="main_group_info">
                    <div class="main_group_photo" style="background-color: #6c6c6c"></div>
                    <div class="main_group_name">
                        <div>
                            {{ group.name }}
                        </div>
                    </div>
                </div>
                <div class="del_line"></div>
                <div class="main_group_description">
                    <h4>{{ group.short_desc }}</h4>
                    <p>{{ group.description }}</p>
                </div>
                <div class="del_line"></div>
                <div class="main_group_buttons">
                    <a href="{% url 'shear:index' id=group.id key=uuid%}" class="main_group_button">add user</a>
                    <a href="{% url 'groups:user_list' id=group.id key=uuid %}" class="main_group_button">user list</a>
                    {% if permission.is_admin or permission.is_creator %}
                        <a href="{% url 'groups:edit_group' id=group.id key=uuid%}" class="main_group_button">edit group</a>
                    {% endif %}
                    <a href="{% url 'groups:remove_user' id=group.id key=uuid%}" class="main_group_button" style="color: #e53935">leave group</a>
                </div>
            </div>
            <div class="group_tasks">
                <h3>Tasks</h3>
                <div class="del_line" style="width: 450px; margin-bottom: 10px"></div>
                <div class="tasks_buttons">
                    {% if permission.is_moderator or permission.is_admin or permission.is_creator %}
                        <a href="{% url 'groups:new_task' id=group.id%}" class="tasks_button">
                            add task
                        </a>
                    {% else %}
                        <a class="tasks_button_un_active">
                            add task
                        </a>
                    {% endif %}
                    <a href="{% url 'groups:all_tasks' key=group.uuid %}" class="tasks_button">
                        all tasks
                    </a>
                </div>
                <div class="del_line" style="width: 450px; margin-bottom: 10px"></div>
                <div class="active_tasks">
                    <h4>Active: 4/10</h4>
                    <a href="" class="active_task">
                        <div style="display: flex; height: 30px; justify-content: space-between">
                            <p class="active_task_name">Lorem ipsum dolor.</p>
                            <p class="active_task_name">Lorem ipsum.</p>
                        </div>
                        <p class="active_task_text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus eveniet in mollitia nulla reiciendis, sunt...</p>
                    </a>
                    <a href="" class="active_task">
                        <div style="display: flex; height: 30px; justify-content: space-between">
                            <p class="active_task_name">Lorem ipsum dolor.</p>
                            <p class="active_task_name">Lorem ipsum.</p>
                        </div>
                        <p class="active_task_text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus eveniet in mollitia nulla reiciendis, sunt...</p>
                    </a>
                    <a href="" class="active_task">
                        <div style="display: flex; height: 30px; justify-content: space-between">
                            <p class="active_task_name">Lorem ipsum dolor.</p>
                            <p class="active_task_name">Lorem ipsum.</p>
                        </div>
                        <p class="active_task_text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus eveniet in mollitia nulla reiciendis, sunt...</p>
                    </a>
                    <a href="" class="active_task">
                        <div style="display: flex; height: 30px; justify-content: space-between">
                            <p class="active_task_name">Lorem ipsum dolor.</p>
                            <p class="active_task_name">Lorem ipsum.</p>
                        </div>
                        <p class="active_task_text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus eveniet in mollitia nulla reiciendis, sunt...</p>
                    </a>
                </div>
            </div>
            <div class="group_users">
                <h3>Users</h3>
                <div class="del_line" style="width: 176px; margin-bottom: 10px"></div>
                {% for i in all_users %}
                    <a href="{% url 'auth:profile' id=i.user.id %}" class="group_user">
                        <div class="user_photo"></div>
                        <div class="user_name">
                            <div style="display: flex">
                                <p>{{ i.user.first_name }}</p>
                                <div class="online_dot"></div>
                            </div>
                            <p>{{ i.user.last_name }}</p>
                        </div>
                    </a>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <div class="pass">
            <div class="pass">
            <p class="pass_text">You must login or register to get access to group</p>
            <div style="display: flex; justify-content: center; margin-top: 20px">
                <a href="{% url 'auth:login' %}" class="pass_button" style="margin-right: 20px">Login</a>
                <a href="{% url 'auth:register' %}" class="pass_button">Register</a>
            </div>
        </div>
        </div>
    {% endif %}
{% endblock %}

groupsapp/templates/groupsapp/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ page_title }}
        {% endblock %}
    </title>
    {% block css %}
        <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,40.." rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}

    {% block js %}

    {% endblock %}

</head>
<body>
<div class="container">
    {% block header %}
    <div class="header">
        <a href="{% url 'index' %}"><img class="logo" src="{% static 'img/logo.svg' %}" alt="logo"></a>
        <ul class="menu">
            <li class="menu-list">
                <a href="{% url 'index' %}" class="menu-link">Home</a>
            </li>
            <li class="menu-list">
                <a href="{% url 'groups:index' %}" class="menu-link menu-link-active">Groups</a>
            </li>
            <li class="menu-list">
                <a href="{% url 'contact' %}" class="menu-link">Contact</a>
            </li>
            {% if user.is_authenticated %}
                <li class="menu-list">
                    <a href="{% url 'auth:profile' id=request.user.id %}" class="menu-link">My profile</a>
                </li>
                <li class="menu-list">
                    <a href="{% url 'auth:logout' %}" class="menu-link">Logout</a>
                </li>
            {% else %}
                <li class="menu-list">
                    <a href="{% url 'auth:login' %}" class="menu-link">Login</a>
                </li>
                <li class="menu-list">
                    <a href="{% url 'auth:register' %}" class="menu-link">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
    {% endblock %}
    <div class="content">
        {% block content %}

        {% endblock %}
    </div>
    {% block footer %}
    <div class="footer">
        <div class="footer_up">
            <div class="footer_contact">
                <h6>CONTACT US</h6>
                <p>QJJR+3R Central Administrative Okrug, Moscow</p>
                <p>Talk to us on +7(123)456-78-90 info@info.com</p>
            </div>
            <div class="footer_useful_info">
                <h6>USEFUL INFORMATION</h6>
                <div class="footer_useful_info_block">
                    <div class="footer_useful_info_links">
                        <a href="{% url 'dev' %}">About Us</a>
                        <a href="{% url 'dev' %}">API</a>
                        <a href="{% url 'dev' %}">Documentation</a>
                    </div>
                    <div class="footer_useful_info_links">
                        <a href="{% url 'dev' %}" target="_blank">Trello</a>
                        <a href="{% url 'dev' %}" target="_blank">Github</a>
                        <a href="{% url 'dev' %}" target="_blank">Seo</a>
                    </div>
                </div>
            </div>
            <div class="footer_touch_email">
                <h6>LET’S STAY IN TOUCH!</h6>
                <p>Subscribe to know about our latest news, products and special offers just for subscribers</p>
                <label>
                    <input type="email" class="footer_touch_email_input" placeholder="your email address">
                </label>
            </div>
        </div>
        <div class="footer_down">
            <p>© Copyright - GROUP UP 2019. All Rights Reserved.</p>
            <div style="display: flex">
                <a href="{% url 'dev' %}" target="_blank"><img src="{% static 'img/facebook_link_logo.png' %}" alt="facebook logo"></a>
                <a href="{% url 'dev' %}" target="_blank"><img src="{% static 'img/twitter_link_logo.png' %}" alt="twitter logo"></a>
                <a href="{% url 'dev' %}" target="_blank"><img src="{% static 'img/google_link_logo.png' %}" alt="google logo"></a>
                <a href="{% url 'dev' %}" target="_blank"><img src="{% static 'img/patreon_link_logo.png' %}" alt="patreon logo"></a>
            </div>
            <a href="{% url 'dev' %}" class="footer_down_privacy_link">TERMS & CONDITIONS / PRIVACY POLICY & COOKIES</a>
        </div>
    </div>
    {% endblock %}
</div>
</body>
</html>

groupsapp/templates/groupsapp/shear.html
{% extends 'groupsapp/layout.html' %}
{% load static %}

{% block content %}
    <div class="pass">
        {{ shear_url }}
        <img src="https://api.qrserver.com/v1/create-qr-code/?size=300x300&data={{ shear_url }}" alt="" class="qr_cod">
    </div>
{% endblock %}